project_id = "ddzyrijgptelvskslaac"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
external_url = "https://ddzyrijgptelvskslaac.supabase.co"

[db]
enabled = true
port = 54322
shadow_port = 54320
major_version = 15

[edge_functions]
enabled = true
port = 54323

[functions.create-checkout-session]
verify_jwt = false

[functions.subscription-audit]
verify_jwt = false